/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "panoply.h"


void
panoplyprog_1(char *host)
{
	CLIENT *clnt;
	boolean  *result_1;
	compte  creercompte_1_arg;
	boolean  *result_2;
	compte  seconnecter_1_arg;
	compte  *result_3;
	int  affichercompte_1_arg;
	int  *result_4;
	char *nombrecompte_1_arg;
	boolean  *result_5;
	abonnement  creerabonnement_1_arg;
	int  *result_6;
	char *nombreabonnement_1_arg;
	abonnement  *result_7;
	int  afficherabonnement_1_arg;
	boolean  *result_8;
	abonnement  majunabonnement_1_arg;
	boolean  *result_9;
	compte  affectationabonnement_1_arg;
	boolean  *result_10;
	collection  creercollection_1_arg;
	int  *result_11;
	char *nombrecollection_1_arg;
	collection  *result_12;
	int  affichercollection_1_arg;
	boolean  *result_13;
	vetement  associervetementcollection_1_arg;
	boolean  *result_14;
	vetement  creervetement_1_arg;
	vetement  *result_15;
	int  affichervetement_1_arg;
	int  *result_16;
	char *nombrevetement_1_arg;
	boolean  *result_17;
	location  louervetement_1_arg;
	int  *result_18;
	char *nombrelocation_1_arg;
	location  *result_19;
	int  afficherlocation_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PANOPLYPROG, PANOPLYVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = creercompte_1(&creercompte_1_arg, clnt);
	if (result_1 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = seconnecter_1(&seconnecter_1_arg, clnt);
	if (result_2 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = affichercompte_1(&affichercompte_1_arg, clnt);
	if (result_3 == (compte *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = nombrecompte_1((void*)&nombrecompte_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = creerabonnement_1(&creerabonnement_1_arg, clnt);
	if (result_5 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = nombreabonnement_1((void*)&nombreabonnement_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = afficherabonnement_1(&afficherabonnement_1_arg, clnt);
	if (result_7 == (abonnement *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = majunabonnement_1(&majunabonnement_1_arg, clnt);
	if (result_8 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = affectationabonnement_1(&affectationabonnement_1_arg, clnt);
	if (result_9 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = creercollection_1(&creercollection_1_arg, clnt);
	if (result_10 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = nombrecollection_1((void*)&nombrecollection_1_arg, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = affichercollection_1(&affichercollection_1_arg, clnt);
	if (result_12 == (collection *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = associervetementcollection_1(&associervetementcollection_1_arg, clnt);
	if (result_13 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = creervetement_1(&creervetement_1_arg, clnt);
	if (result_14 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_15 = affichervetement_1(&affichervetement_1_arg, clnt);
	if (result_15 == (vetement *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_16 = nombrevetement_1((void*)&nombrevetement_1_arg, clnt);
	if (result_16 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_17 = louervetement_1(&louervetement_1_arg, clnt);
	if (result_17 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_18 = nombrelocation_1((void*)&nombrelocation_1_arg, clnt);
	if (result_18 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_19 = afficherlocation_1(&afficherlocation_1_arg, clnt);
	if (result_19 == (location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	panoplyprog_1 (host);
exit (0);
}
