/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "panoply.h"

bool_t
xdr_abonnement (XDR *xdrs, abonnement *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->identifiant))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nomabn, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nombreCredit))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_typeCompte (XDR *xdrs, typeCompte *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_step (XDR *xdrs, step *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->jour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_engagement (XDR *xdrs, engagement *objp)
{
	register int32_t *buf;

	 if (!xdr_abonnement (xdrs, &objp->abn))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->debut))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->fin))
		 return FALSE;
	 if (!xdr_step (xdrs, &objp->etat))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_compte (XDR *xdrs, compte *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->identifiant))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mdp, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->adresse, 250,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_engagement (xdrs, &objp->monEngagement))
		 return FALSE;
	 if (!xdr_typeCompte (xdrs, &objp->monType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_collection (XDR *xdrs, collection *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomCollection, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idCollection))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_marque (XDR *xdrs, marque *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomMarque, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idMarque))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_occasion (XDR *xdrs, occasion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomOccasion, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idOccasion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vetement (XDR *xdrs, vetement *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->nomVetement, 100,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->prixVetement))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nbCredit))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->idVetement))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nbExemplaire))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->prixVetement);
		IXDR_PUT_LONG(buf, objp->nbCredit);
		IXDR_PUT_LONG(buf, objp->idVetement);
		IXDR_PUT_LONG(buf, objp->nbExemplaire);
		}
		 if (!xdr_collection (xdrs, &objp->maCollection))
			 return FALSE;
		 if (!xdr_marque (xdrs, &objp->maMarque))
			 return FALSE;
		 if (!xdr_occasion (xdrs, &objp->monOccasion))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->nomVetement, 100,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->prixVetement))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nbCredit))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->idVetement))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nbExemplaire))
				 return FALSE;

		} else {
		objp->prixVetement = IXDR_GET_LONG(buf);
		objp->nbCredit = IXDR_GET_LONG(buf);
		objp->idVetement = IXDR_GET_LONG(buf);
		objp->nbExemplaire = IXDR_GET_LONG(buf);
		}
		 if (!xdr_collection (xdrs, &objp->maCollection))
			 return FALSE;
		 if (!xdr_marque (xdrs, &objp->maMarque))
			 return FALSE;
		 if (!xdr_occasion (xdrs, &objp->monOccasion))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->nomVetement, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prixVetement))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbCredit))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idVetement))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbExemplaire))
		 return FALSE;
	 if (!xdr_collection (xdrs, &objp->maCollection))
		 return FALSE;
	 if (!xdr_marque (xdrs, &objp->maMarque))
		 return FALSE;
	 if (!xdr_occasion (xdrs, &objp->monOccasion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tj_vetement_collection (XDR *xdrs, tj_vetement_collection *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->vetement_de_la_collection, 1000,
		sizeof (vetement), (xdrproc_t) xdr_vetement))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nombre))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tj_vetement_marque (XDR *xdrs, tj_vetement_marque *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->vetement_de_la_marque, 1000,
		sizeof (vetement), (xdrproc_t) xdr_vetement))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nombre))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tj_vetement_occasion (XDR *xdrs, tj_vetement_occasion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->vetement_de_l_occasion, 1000,
		sizeof (vetement), (xdrproc_t) xdr_vetement))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nombre))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_stepLocation (XDR *xdrs, stepLocation *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_date (xdrs, &objp->debut_location))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->fin_location))
		 return FALSE;
	 if (!xdr_stepLocation (xdrs, &objp->etatDeLaLocation))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->identifiantClient))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->identifiantVetement))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->identifiantLocation))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_boolean (XDR *xdrs, boolean *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
