/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "panoply.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
panoplyprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		new_member_params register_1_arg;
		login_member_params login_1_arg;
		int show_member_1_arg;
		subscription_t new_subscription_1_arg;
		int show_subscription_1_arg;
		subscription_t update_subscription_1_arg;
		set_member_subscription_params set_member_subscription_1_arg;
		new_collection_params new_collection_1_arg;
		int show_collection_1_arg;
		set_clothing_collection_params set_clothing_collecton_1_arg;
		new_clothing_params new_clothing_1_arg;
		int show_clothing_1_arg;
		int rent_clothing_1_arg;
		int show_rental_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REGISTER:
		_xdr_argument = (xdrproc_t) xdr_new_member_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) register_1_svc;
		break;

	case LOGIN:
		_xdr_argument = (xdrproc_t) xdr_login_member_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) login_1_svc;
		break;

	case TOTAL_MEMBERS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) total_members_1_svc;
		break;

	case SHOW_MEMBER:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_member_t;
		local = (char *(*)(char *, struct svc_req *)) show_member_1_svc;
		break;

	case NEW_SUBSCRIPTION:
		_xdr_argument = (xdrproc_t) xdr_subscription_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) new_subscription_1_svc;
		break;

	case TOTAL_SUBSCRIPTIONS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) total_subscriptions_1_svc;
		break;

	case SHOW_SUBSCRIPTION:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_subscription_t;
		local = (char *(*)(char *, struct svc_req *)) show_subscription_1_svc;
		break;

	case UPDATE_SUBSCRIPTION:
		_xdr_argument = (xdrproc_t) xdr_subscription_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) update_subscription_1_svc;
		break;

	case SET_MEMBER_SUBSCRIPTION:
		_xdr_argument = (xdrproc_t) xdr_set_member_subscription_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_member_subscription_1_svc;
		break;

	case NEW_COLLECTION:
		_xdr_argument = (xdrproc_t) xdr_new_collection_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) new_collection_1_svc;
		break;

	case TOTAL_COLLECTIONS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) total_collections_1_svc;
		break;

	case SHOW_COLLECTION:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_collection_t;
		local = (char *(*)(char *, struct svc_req *)) show_collection_1_svc;
		break;

	case SET_CLOTHING_COLLECTON:
		_xdr_argument = (xdrproc_t) xdr_set_clothing_collection_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_clothing_collecton_1_svc;
		break;

	case NEW_CLOTHING:
		_xdr_argument = (xdrproc_t) xdr_new_clothing_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) new_clothing_1_svc;
		break;

	case TOTAL_CLOTHINGS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) total_clothings_1_svc;
		break;

	case SHOW_CLOTHING:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_cloth_t;
		local = (char *(*)(char *, struct svc_req *)) show_clothing_1_svc;
		break;

	case RENT_CLOTHING:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rent_clothing_1_svc;
		break;

	case TOTAL_RENTS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) total_rents_1_svc;
		break;

	case SHOW_RENTAL:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_rental_t;
		local = (char *(*)(char *, struct svc_req *)) show_rental_1_svc;
		break;

	case LIST_CLOTHES:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_clothes_list_t;
		local = (char *(*)(char *, struct svc_req *)) list_clothes_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PANOPLYPROG, PANOPLYVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PANOPLYPROG, PANOPLYVERS, panoplyprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PANOPLYPROG, PANOPLYVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PANOPLYPROG, PANOPLYVERS, panoplyprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PANOPLYPROG, PANOPLYVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
